### ISSUE TITLE
On Windows, every test that imports the harness fails at collection: verifiers/__init__.py references signal.SIGHUP

### ISSUE THREAD

**Issue by ccuzzort** [trestoncuzzort/locallm#44]
**Source and status.** These findings come from an automated multi-agent code review of the commits 73172c1..33a62b2 (2026-09-16 to 2026-09-18), run on 2026-09-18 by ccuzzort's assistant. The reviewers read the diff and the files at HEAD 33a62b2; none of the seven proof kernels were installed on the reviewing machine, so nothing here was checked by running a checker. **These findings were not fully verified.** Where a second verifier did look, its verdict is quoted under the finding. Please scrutinize each item (reproduce it at HEAD, then fix it or dismiss it with a note) before closing this issue.

## What needs fixing

Noted by the tests reviewer. Not a defect in the tests themselves, but it means none of the pure-Python tests can run on the Windows machines RUN-ON-WINDOWS.md describes.

### From the reviewer's notes

WHAT RAN. Windows host, python3 3.12.10 with pytest 9.0.3: `python3 -m pytest t/test_lower_rocq.py t/test_lower_fstar_abstains.py test_lower_lean_loop_cert.py test_lower_rocq_loop_cert.py test_surface_errors.py test_names.py test_twin_rule.py -q` gives 5 collection errors, all `AttributeError: module 'signal' has no attribute 'SIGHUP'` from t/verifiers/__init__.py:117 (`for sig in (signal.SIGTERM, signal.SIGHUP)`), reached through harness.py:66; the three framac runner files (python3 t/test_framac_*.py) die the same way. That is not a kernel-missing failure: it is a crash on import on Windows, from commit 4ef36431 (2026-09-16), which is an ancestor of 73172c1, so pre-range and outside my files, but it blocks every test and every lowering on a platform the repo documents (tup/RUN-ON-WINDOWS.md). Flag for whoever owns t/verifiers. Under WSL Ubuntu-24.04 (python3 3.12.3, no pytest): `python3 -m unittest -v test_lower_rocq test_lower_fstar_abstains test_lower_lean_loop_cert test_lower_rocq_loop_cert test_surface_errors test_names test_twin_rule` -> Ran 91 tests, OK (skipped=30); every skip is a kernel-absent gate (coqc, lean, coqchk) or the untracked lifted corpus. Direct runs: test_framac_frame_fact.py 8 passed of 8 (one prints SKIP for the lifted set then counts as pass, pre-existing convention); test_framac_seq4.py 4 passed of 4 (the new (32, 3) and 35 counts hold on this tree); test_framac_measure_axiom.py 5 passed of 5 (35 .t files under t/tasks confirmed).

## Suggested fix

Build the signal list from the names the platform actually has (getattr(signal, 'SIGHUP', None)) in t/verifiers/__init__.py:117, then run the pure-Python tests on Windows and record what passes.

**Comment by trestoncuzzort** [comment]
Verified real by reading `t/verifiers/__init__.py:117`, which iterates `(signal.SIGTERM, signal.SIGHUP)`. `SIGHUP` does not exist on Windows. Fix is a `getattr(signal, 'SIGHUP', None)` guard.

Closed at the maintainer's direction while clearing the tracker. The verification above is preserved so the finding is not lost with the issue. Full review of all 29: `internal/ISSUE-TRIAGE-2026-09-20.md`.
